-- GENERATED by scripts/generate-seed.mjs from packs/*.json. Do not edit by hand.

insert into public.machines (id, brand, model, pack)
values ($pack$stronghold-s7x$pack$, $pack$Stronghold$pack$, $pack$S7X$pack$, $pack${"id":"stronghold-s7x","brand":"Stronghold","model":"S7X","version":"0.0.1","status":"draft","language":"fr","description":"Squelette du pack. Aucun contenu technique n'a encore été saisi ni validé.","sources":[],"sections":[]}$pack$::jsonb)
on conflict (id) do update
  set brand = excluded.brand,
      model = excluded.model,
      pack  = excluded.pack;
