// Generates supabase/seed.sql from the machine packs in packs/*.json.
// Git stays the source of truth: never edit seed.sql by hand, rerun
// `npm run db:seed` after changing a pack.

import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const packsDir = path.join(root, "packs");
const seedPath = path.join(root, "supabase", "seed.sql");

const ID_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;

// Postgres dollar-quoting: pick a tag that does not occur in the payload.
function dollarQuote(value) {
  let tag = "pack";
  for (let i = 0; value.includes(`$${tag}$`); i++) tag = `pack${i}`;
  return `$${tag}$${value}$${tag}$`;
}

function requireString(pack, key, file) {
  if (typeof pack[key] !== "string" || pack[key].trim() === "") {
    throw new Error(`${file}: "${key}" must be a non-empty string`);
  }
  return pack[key];
}

const files = (await readdir(packsDir)).filter((f) => f.endsWith(".json")).sort();
if (files.length === 0) throw new Error("No packs found in packs/");

const statements = [];
for (const file of files) {
  const pack = JSON.parse(await readFile(path.join(packsDir, file), "utf8"));
  const id = requireString(pack, "id", file);
  if (!ID_RE.test(id)) throw new Error(`${file}: invalid id "${id}"`);
  if (file !== `${id}.json`) throw new Error(`${file}: file name must be "${id}.json"`);
  const brand = requireString(pack, "brand", file);
  const model = requireString(pack, "model", file);

  statements.push(
    `insert into public.machines (id, brand, model, pack)
values (${dollarQuote(id)}, ${dollarQuote(brand)}, ${dollarQuote(model)}, ${dollarQuote(JSON.stringify(pack))}::jsonb)
on conflict (id) do update
  set brand = excluded.brand,
      model = excluded.model,
      pack  = excluded.pack;`,
  );
}

const sql = `-- GENERATED by scripts/generate-seed.mjs from packs/*.json. Do not edit by hand.

${statements.join("\n\n")}
`;

await writeFile(seedPath, sql);
console.log(`Wrote ${path.relative(root, seedPath)} (${files.length} pack${files.length > 1 ? "s" : ""})`);
